apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  releaseName: keda

  chart:
    spec:
      chart: keda
      version: "2.14.0"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: keda-values
      valuesKey: values.yaml
